name: basic
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/I4annet/dart-basics

environment:
  sdk: ^3.9.1

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
